### PR TITLE
A few minor SSL updates

### PR DESCRIPTION
**Pull request by DrDoug88**
Thanks for putting this image together. I made a few minor updates to the SSL, namely running update-ca-certificates at the beginning of the entrypoint.sh script. This allows any certificates mounted into the /usr/local/share/ca-certificates directory to be added to the trusted CA store.  Then, if there is anything stored in that directory, then smtpd_tls_CAfile points to /etc/ssl/certs/ca-certificates.crt rather than /etc/postfix/tls/rootCA.crt. I also explicitly set smtp_tls_CAfile=/etc/ssl/certs/ca-certificates.crt, Unfortunately, this last edit could not be accomplished by setting it as a RAW_CONFIG, since the CA is upper-case and the raw config process forces everything to be lower case.

### CODE REVIEW

**Comment by MarvAmBass** [comment]
Hi Doug, thanks for your work! Good idea to import all existing CAs into the trusted store on container start.

unfortunately this breaks my curreny configuration, so I'll have to migrate to your new way before I can merge.

thanks and kind regards! maybe I'll even find a solution for the uppercase env parsing

**Comment by DrDoug88** [comment]
Hi Marv,

I'm not sure how it would break your existing configuration if you didn't mount any certificates in the /usr/local/share/ca-certificates directory, the logic only changes if the directory is not empty, unless you're referring to the smtp_tls_CAfile change. Anyhow, thanks for your response. 

On that note, I am trying to put together and configure a gateway relay server in a specific way, and your project addresses my requirements better than any other that I could find. I ran into issues with DKIM signing, but I would rather let that be handled upstream by the internal servers. I also had troubles with the fingerprint matching as well. I'll follow up better with these problems shortly. Here is a description of what I am trying to set up. I am a bit new to Postfix, I have been reading from numerous sources as well as the official documentation over the past week or two to get a firm grasp of the settings.  I understand that many of these you already have implemented, some of them just require some additional settings, and some are not implemented at all. If you have any insight on these items, please let me know: 

------------------------------------
### Gateway mail relay for incoming and outgoing emails for a network of internal mail servers

### OUTGOING RELAY SUBMISSIONS

- Only clients that are in mynetworks and with matching certificate fingerprint can submit mail for relay.
- Configure next hop relayhosts, i.e. Sendinblue, Mailgun, etc. for certain destinations, in case the IP address of the Postfix server is on a recipient server's blocklist, i.e. Microsoft, Gmail, etc.
- Verify DKIM (generated by internal mail server) of outgoing mail before sending to prevent generation of spam and internal spoofing, i.e. reject any failed signatures. This will help build the reputation of the Postfix server's IP address and notify of a misconfiguration.
- Provide option to add DKIM signature.
- Relay between internal mail servers (should be automatic based on transport map)

### INCOMING MAIL RECEIPT
- Accept mail from anywhere if the recipient/domain is listed in the transport map.
- Option to perform basic spam filtering, i.e. Amavis, with an option to set the threshold spam score.
- Option to perform antivirus scanning, i.e. Clamd


### OVERALL SECURITY

- Lock down all other settings, i.e. smtpd_sender_restrictions, smtpd_recipient_restrictions, smtpd_relay_restrictions, etc. to prevent any unintended/unauthorized use of the Postfix server.
- Fail2Ban for intrusion detection/prevention
------------------------------------

**Comment by MarvAmBass** [comment]
it's broken because you added a new trusted party

```
smtpd_recipient_restrictions=permit_mynetworks,permit_tls_all_clientcerts,reject_unauth_destination
```

`permit_tls_all_clientcerts` could be a really bad security choice, especially when there are other trusted CAs you're not aware of. I consider this kinda risky to be honest.

I would only trust one specific CA if I use it for some kind of mtls tunnel between my own servers.
and this can already be done


to your other questions. fail2ban seems nice, but this means you need to run your container on your host network - I haven't had the time to get a nice fail2ban config for docker/k8s setup.

all other points are already implemented.

architecture as follows

- mail-gateway container 
    - _1_ to be used to enable any container to send / relay mail (permit mynetworks because it is considered to run alongside with the container who wants to sent mails and is therefore in a specific trusted environment with this specific container)
    - you need to make sure to use mynetworks only in cases where there is no risk for others to sent mail via this gateway
    - _2_ can be used to forward and sign your internal emails from my containers like (mail-box, minimail) to the mail relay in the internet - here you need to setup a mtls tunnel so that only your trusted relay is able to sent mails via your internet accesible gateway - you can also use a vpn, but since postfix already supports tls client auth I personally think it's way easier
    - _3_ it can act as a incoming smtp gateway which handles and caches all incoming emails for domains you control and forward it to a hidden/private mail server (e.g. mail-box, minimail)
    - _4_ it can act as an outgoing internet smtp gateway and cache to avoid anti spam mechanisms for smtp servers on private internet connections -> mtls or vpn only!


_Note:_ operating your own mailserver is a really really big task! with all the anti spam mechanisms and pitfalls you should really know what you're doing and what the risks are. even if you know everything you will have trouble with some providers not accepting your mail (I never had that problem with private emails, but in a company with many users and emails this happens)

even if this might sound bad and not inclusive etc. -> if you have no working experience or do not work in IT and only do this as a hobbist you should not run your own mailserver.
I wish it was possible, to liberate the internet and especially mailing, but looking at the current situation even as a IT professional it's not an easy task!

currently you need to look into all anti spam measures available and implement everything, so your emails can be trusted
opendkim, spf header. most of it requires you to have access to your domains dns server settings


hope this helps

**Comment by DrDoug88** [comment]
Hi Marv,

You're right, adding all of the certificates in the store breaks the MTLS, I'm an idiot. I have only spent a week or so reading up on Postfix. I think I have it all figured out. I'm only looking into putting together a good Postfix gateway relay server, not the entire mail system. My background is in ML/data science and software engineering in classical OOP languages. I have only gotten interested in front end web tech recently. It's actually much simpler...a lot of tedious configuration details though. Thanks for your help. I'll post my updates shortly.

D

**Comment by DrDoug88** [comment]
BTW, here is a project that incorporated Fail2Ban with a Postfix container in Docker:

https://github.com/danil-smirnov/docker-postfix

And a blog article on it:

https://blog.smirnov.la/postfix-in-docker-5bf01e425a47

**Comment by MarvAmBass** [comment]
Hi there, 

updating ca-certs is not generally a bad idea, if you have a public facing mail gateway you might want it to trust a few other servers when sending mails to them.
but the client cert auth doesn't make sense then.

in postfix you always need to be carefull if its the config for recieving or sending :D if you mix that up you can get in trouble.

I don't doubt that you're not capable, just that one thinks for himself if this is a task he is ready to take.

regardings the fail2ban config examples, those will rarely work in a mail container with least privileges.
it won't block proper ips, might block the whole incoming traffic at once and shouldn't have the permissions to alter firewall rules.

best installation would be, to somehow analyse the logs (which are collected and analyzed in a central log managing system) and give informations about who to block to the main/public firewall of the network

**Comment by DrDoug88** [comment]
Hi Marv,

Thanks for the response. The reason that I included update-ca-certificates is to allow for verified client connections with both external and internal CAs. I clearly see how this can lead to an open relay when you allow for verified connections to relay.  You are indeed correct that the logic can get mixed up and confusing when dealing with internal clients that you want to provide relay services while blocking external clients from having the ability solely on port 25. I am changing it all up and instead I'm going to use the submission port (587) for outgoing relay services and only using port 25 for relaying incoming mail.  I'll post a working setup in the next few days.

**Comment by DrDoug88** [comment]
Hi Marv,

I have implemented the changes for my use case. You can look through my fork to see it all. I think it significantly diverges from your implementation. So I'm not sure that you would be looking to pull it. I'd be happy to if you want though. Anyhow, I did want to bring up a few things. First, I had struggled with the fingerprint method, and finally figured out that it was the smtp_tls_fingerprint_digest which was giving me problems. The default in postfix is MD5, which is severely outdated. I explicitly set it to sha256 and indicated the same when generating the fingerprints using openssl (the default method in openssl is sha1). Another item that I had to add in order for header_checks to work for the submission daemon was a custom cleanup process.  I also added libmail-spf-perl to the Dockerfile to enable spf checks. I didn't need DKIM signing so I got rid of it entirely.  Amavis performs a dkim verification check via the spamassassin libraries to calculate the spam score, so that as sufficient for my needs. Anyhow, thank you again for posting your project as well as your responses and feedback, you really got me going in the right direction. 

D

**Comment by MarvAmBass** [comment]
Hi sounds like a lot of work. and that I should take some time to also implement spf checks and upgrade the hashing to sha256.

You're right, I wouldn't pull it - but feel free to add the pull request - this way others can compare, and I can take a look and cherry pick some nice to have options.

thanks and good luck!

**Pull request closed without merging**
